bioimageio_core_version: 0.5.9
bioimageio_spec_version: 0.4.9.post1
rdf_sha256: 3dbe2c5783d3492d4f2323148da32bef92e1dc139cde9d38d86c582d63ce3c9a
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.9post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.9 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags corresponding to bioimage.io categories: [{''modality'':
        [''electron-microscopy'', ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'',
        ''transmission-light-microscopy'', ''super-resolution-microscopy'', ''x-ray-microscopy'',
        ''force-microscopy'', ''high-content-imaging'', ''whole-slide-imaging'', ''other'']},
        {''dims'': [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''content'': [''cells'',
        ''nuclei'', ''extracellular-vesicles'', ''tissue'', ''plant'', ''mitochondria'',
        ''vasculature'', ''cell-membrane'', ''brain'', ''whole-organism'']}, {''framework'':
        [''tensorflow'', ''pytorch'', ''tensorflow.js'']}, {''network'': [''unet'',
        ''densenet'', ''resnet'', ''inception'', ''shufflenet'']}]'}
  - bioimageio_spec_version: 0.4.9post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.3.6
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags corresponding to bioimage.io categories: [{''modality'':
        [''electron-microscopy'', ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'',
        ''transmission-light-microscopy'', ''super-resolution-microscopy'', ''x-ray-microscopy'',
        ''force-microscopy'', ''high-content-imaging'', ''whole-slide-imaging'', ''other'']},
        {''dims'': [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''content'': [''cells'',
        ''nuclei'', ''extracellular-vesicles'', ''tissue'', ''plant'', ''mitochondria'',
        ''vasculature'', ''cell-membrane'', ''brain'', ''whole-organism'']}, {''framework'':
        [''tensorflow'', ''pytorch'', ''tensorflow.js'']}, {''network'': [''unet'',
        ''densenet'', ''resnet'', ''inception'', ''shufflenet'']}]'}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9post4
    error: null
    name: load resource description
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9post4
    error: https://github.com/bioimage-io/fiji-bioimage-io/releases/download/0.3.1/n2v-sem-demo.zip
    name: All URLs and paths available
    nested_errors: null
    status: failed
    traceback: ["  File \"/home/runner/micromamba/envs/latest/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 87, in _test_resource_urls\n    SourceNodeChecker(root_path=rd.root_path).visit(rd)\n",
      "  File \"/home/runner/micromamba/envs/latest/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 34, in visit\n    visitor(node)\n", "  File \"/home/runner/micromamba/envs/latest/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 52, in generic_visit\n    self.visit(value)\n", "  File \"/home/runner/micromamba/envs/latest/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 34, in visit\n    visitor(node)\n", "  File \"/home/runner/micromamba/envs/latest/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 38, in visit_URI\n    self._visit_source(node)\n", "  File \"/home/runner/micromamba/envs/latest/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 35, in _visit_source\n    raise FileNotFoundError(leaf)\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9post4
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9post4
    error: Cannot load file containing pickled data when allow_pickle=False
    name: reproduce test outputs from test inputs (bioimageio.core 0.5.9)
    status: failed
    traceback: ["  File \"/home/runner/micromamba/envs/latest/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 135, in _test_model_inference\n    inputs = [np.load(str(in_path)) for
        in_path in model.test_inputs]\n", "  File \"/home/runner/micromamba/envs/latest/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 135, in <listcomp>\n    inputs = [np.load(str(in_path)) for in_path in
        model.test_inputs]\n", "  File \"/home/runner/micromamba/envs/latest/lib/python3.7/site-packages/numpy/lib/npyio.py\",
        line 445, in load\n    raise ValueError(\"Cannot load file containing pickled
        data \"\n"]
    warnings: {}
  deepimagej:
  - {bioimageio_core_version: 0.5.9, bioimageio_spec_version: 0.4.9, error: Error
      while running DeepImageJ headless (CI did not produce an output image)., name: Reproduce
      test outputs with DeepImageJ headless., status: failed}
  ilastik:
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: local variable 'rd' referenced before assignment
    name: reproduce test outputs with ilastik 1.4.0rc8 using tensorflow_saved_model_bundle
      weights
    nested_errors: null
    status: failed
    traceback: ["  File \"/home/runner/work/bioimage-io-resources/bioimage-io-resources/scripts/test_with_ilastik.py\",
        line 82, in run_tests\n    summaries = test_model(rdf_path, weight_format=weight_format)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 41, in test_model\n    model_rdf, weight_format=weight_format, devices=devices,
        decimal=decimal, expected_type=\"model\"\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 250, in test_resource\n    rd, load_test = _test_load_resource(rdf, weight_format)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 224, in _test_load_resource\n    return rd, load_summary\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: '{''_schema'': [''Minimal shape [1. 4. 4. 1.] of output denoised is too
      small for halo [0, 32, 32, 0].'']}'
    name: load resource description
    nested_errors: null
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 202, in _test_load_resource\n    rdf, weights_priority_order=None if
        weight_format is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
        line 47, in load_resource_description\n    raw_rd = load_raw_resource_description(source,
        update_to_format=\"latest\")\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/io_.py\",
        line 231, in load_raw_resource_description\n    raise e\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/io_.py\",
        line 223, in load_raw_resource_description\n    raw_rd = schema.load(data)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/marshmallow/schema.py\",
        line 723, in load\n    data, many=many, partial=partial, unknown=unknown,
        postprocess=True\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/marshmallow/schema.py\",
        line 909, in _do_load\n    raise exc\n"]
    warnings: {}
