bioimageio_core_version: 0.5.9
bioimageio_spec_version: 0.4.9
rdf_sha256: b2898b326dfa5f2374ba008c8ba7e4e483d3ac16f29357bc0b457cbd8166758c
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.9
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.9 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags corresponding to bioimage.io categories: [{''modality'':
        [''electron-microscopy'', ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'',
        ''transmission-light-microscopy'', ''super-resolution-microscopy'', ''x-ray-microscopy'',
        ''force-microscopy'', ''high-content-imaging'', ''whole-slide-imaging'', ''other'']},
        {''software'': [''ilastik'', ''imagej'', ''fiji'', ''imjoy'', ''deepimagej'',
        ''n2v'']}]'
      weights: {pytorch_state_dict: missing 'pytorch_version'}
  - bioimageio_spec_version: 0.4.9
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.9
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags corresponding to bioimage.io categories: [{''modality'':
        [''electron-microscopy'', ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'',
        ''transmission-light-microscopy'', ''super-resolution-microscopy'', ''x-ray-microscopy'',
        ''force-microscopy'', ''high-content-imaging'', ''whole-slide-imaging'', ''other'']},
        {''software'': [''ilastik'', ''imagej'', ''fiji'', ''imjoy'', ''deepimagej'',
        ''n2v'']}]'
      weights: {pytorch_state_dict: missing 'pytorch_version'}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9
    error: 'Failed to download https://zenodo.org/api/files/045f2183-0b8c-444a-bdd4-02c5a9a40ad0/raw.png
      (500 Server Error: INTERNAL SERVER ERROR for url: https://zenodo.org/api/files/045f2183-0b8c-444a-bdd4-02c5a9a40ad0/raw.png)'
    name: load resource description
    nested_errors: null
    status: failed
    traceback: ["  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\",
        line 201, in _test_load_resource\n    rd: Optional[ResourceDescription] =
        load_resource_description(\n", "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/core/resource_io/io_.py\",
        line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_node(raw_rd=raw_rd,
        nodes_module=nodes)\n", "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\",
        line 121, in resolve_raw_node\n    rd = UriNodeTransformer(root_path=raw_rd.root_path,
        uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)\n", "  File
        \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 56, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 161, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n", "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 161, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n", "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 56, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 62, in transform_list\n    return [self.transform(subnode, **kwargs)
        for subnode in node]\n", "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 62, in <listcomp>\n    return [self.transform(subnode, **kwargs) for
        subnode in node]\n", "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 56, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 339, in transform_URI\n    local_path = _resolve_source(node, root_path=self.root)\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/functools.py\",
        line 888, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 253, in _resolve_source_uri_node\n    local_path = _download_url(path_or_remote_uri,
        output, pbar=pbar)\n", "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.9/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 479, in _download_url\n    raise RuntimeError(f\"Failed to download {uri}
        ({e})\") from e\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9
    error: 'Failed to download https://zenodo.org/api/files/045f2183-0b8c-444a-bdd4-02c5a9a40ad0/pred.png
      (500 Server Error: INTERNAL SERVER ERROR for url: https://zenodo.org/api/files/045f2183-0b8c-444a-bdd4-02c5a9a40ad0/pred.png)'
    name: load resource description
    nested_errors: null
    status: failed
    traceback: ["  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/core/resource_tests.py\",
        line 201, in _test_load_resource\n    rd: Optional[ResourceDescription] =
        load_resource_description(\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/core/resource_io/io_.py\",
        line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_node(raw_rd=raw_rd,
        nodes_module=nodes)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/core/resource_io/utils.py\",
        line 121, in resolve_raw_node\n    rd = UriNodeTransformer(root_path=raw_rd.root_path,
        uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 56, in transform\n    return transformer(node, **kwargs)  # noqa\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 161, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 161, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 56, in transform\n    return transformer(node, **kwargs)  # noqa\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 62, in transform_list\n    return [self.transform(subnode, **kwargs)
        for subnode in node]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 62, in <listcomp>\n    return [self.transform(subnode, **kwargs) for
        subnode in node]\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File
        \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 56, in transform\n    return transformer(node, **kwargs)  # noqa\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 339, in transform_URI\n    local_path = _resolve_source(node, root_path=self.root)\n
        \                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/functools.py\",
        line 909, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n
        \          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 253, in _resolve_source_uri_node\n    local_path = _download_url(path_or_remote_uri,
        output, pbar=pbar)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/runner/micromamba-root/envs/7805026/lib/python3.11/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 479, in _download_url\n    raise RuntimeError(f\"Failed to download {uri}
        ({e})\") from e\n"]
    warnings: {}
  deepimagej:
  - {bioimageio_core_version: 0.5.9, bioimageio_spec_version: 0.4.9, error: Error
      while running DeepImageJ headless (CI did not produce an output image), name: Reproduce
      test outputs with DeepImageJ headless, status: failed}
