bioimageio_spec_version: 0.4.9
rdf_sha256: 0e2650d43589a193642f1bf0bb04d18bb046fa0cf8872f115d136e7b4eba7f6f
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.9
    error:
      _schema: [Referenced tensor input_images with 3 dimensions does not match output
          tensor output_images with 4 dimensions.]
    name: bioimageio.spec static validation of  RDF  with update to latest format
      version
    nested_errors: {}
    status: failed
    traceback: null
    warnings: {tags: 'Missing tags corresponding to bioimage.io categories: [{''modality'':
        [''electron-microscopy'', ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'',
        ''transmission-light-microscopy'', ''super-resolution-microscopy'', ''x-ray-microscopy'',
        ''force-microscopy'', ''high-content-imaging'', ''whole-slide-imaging'', ''other'']},
        {''dims'': [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''content'': [''cells'',
        ''nuclei'', ''extracellular-vesicles'', ''tissue'', ''plant'', ''mitochondria'',
        ''vasculature'', ''cell-membrane'', ''brain'', ''whole-organism'']}, {''framework'':
        [''tensorflow'', ''pytorch'', ''tensorflow.js'']}, {''network'': [''unet'',
        ''densenet'', ''resnet'', ''inception'', ''shufflenet'']}, {''task'': [''semantic-segmentation'',
        ''instance-segmentation'', ''object-detection'', ''image-classification'',
        ''denoising'', ''image-restoration'', ''image-reconstruction'', ''in-silico-labeling'']}]'}
  - bioimageio_spec_version: 0.4.9
    error: null
    name: bioimageio.spec static validation of model RDF 0.3.6
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags corresponding to bioimage.io categories: [{''modality'':
        [''electron-microscopy'', ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'',
        ''transmission-light-microscopy'', ''super-resolution-microscopy'', ''x-ray-microscopy'',
        ''force-microscopy'', ''high-content-imaging'', ''whole-slide-imaging'', ''other'']},
        {''dims'': [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''content'': [''cells'',
        ''nuclei'', ''extracellular-vesicles'', ''tissue'', ''plant'', ''mitochondria'',
        ''vasculature'', ''cell-membrane'', ''brain'', ''whole-organism'']}, {''framework'':
        [''tensorflow'', ''pytorch'', ''tensorflow.js'']}, {''network'': [''unet'',
        ''densenet'', ''resnet'', ''inception'', ''shufflenet'']}, {''task'': [''semantic-segmentation'',
        ''instance-segmentation'', ''object-detection'', ''image-classification'',
        ''denoising'', ''image-restoration'', ''image-reconstruction'', ''in-silico-labeling'']}]'}
  deepimagej:
  - {bioimageio_spec_version: 0.4.8post1, error: Sample image tiffs have not been
      generated from numpy tests files, name: Initial compatibility checks with DeepImageJ,
    status: failed}
  ilastik:
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: '{''_schema'': [''Referenced tensor input_images with 3 dimensions does
      not match output tensor output_images with 4 dimensions.'']}'
    name: load resource description
    nested_errors: null
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 202, in _test_load_resource\n    rdf, weights_priority_order=None if
        weight_format is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
        line 47, in load_resource_description\n    raw_rd = load_raw_resource_description(source,
        update_to_format=\"latest\")\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/io_.py\",
        line 231, in load_raw_resource_description\n    raise e\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/io_.py\",
        line 223, in load_raw_resource_description\n    raw_rd = schema.load(data)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/marshmallow/schema.py\",
        line 723, in load\n    data, many=many, partial=partial, unknown=unknown,
        postprocess=True\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/marshmallow/schema.py\",
        line 909, in _do_load\n    raise exc\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: local variable 'rd' referenced before assignment
    name: reproduce test outputs with ilastik 1.4.0rc8 using tensorflow_saved_model_bundle
      weights
    nested_errors: null
    status: failed
    traceback: ["  File \"/home/runner/work/bioimage-io-resources/bioimage-io-resources/scripts/test_with_ilastik.py\",
        line 82, in run_tests\n    summaries = test_model(rdf_path, weight_format=weight_format)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 41, in test_model\n    model_rdf, weight_format=weight_format, devices=devices,
        decimal=decimal, expected_type=\"model\"\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 250, in test_resource\n    rd, load_test = _test_load_resource(rdf, weight_format)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 224, in _test_load_resource\n    return rd, load_summary\n"]
    warnings: {}
