bioimageio_core_version: 0.5.9
bioimageio_spec_version: 0.4.9
rdf_sha256: 7fe8d26614ed333e1dda9b886f30496522a920049874238596a6a622801c7b64
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.9
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.9 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {license: BSD-2-Clause (BSD 2-Clause "Simplified" License) is not FSF
        Free/libre.}
  - bioimageio_spec_version: 0.4.9
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.9
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {license: BSD-2-Clause (BSD 2-Clause "Simplified" License) is not FSF
        Free/libre.}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9
    error: null
    name: load resource description
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9
    error: https://bioimage-io.github.io/collection-bioimage-io/rdfs/10.5281/zenodo.5914248/8186255/rdf.yaml
    name: All URLs and paths available
    nested_errors: null
    status: failed
    traceback: ["  File \"/home/runner/micromamba/envs/8186255/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 87, in _test_resource_urls\n    SourceNodeChecker(root_path=rd.root_path).visit(rd)\n",
      "  File \"/home/runner/micromamba/envs/8186255/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 34, in visit\n    visitor(node)\n", "  File \"/home/runner/micromamba/envs/8186255/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 52, in generic_visit\n    self.visit(value)\n", "  File \"/home/runner/micromamba/envs/8186255/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 34, in visit\n    visitor(node)\n", "  File \"/home/runner/micromamba/envs/8186255/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 38, in visit_URI\n    self._visit_source(node)\n", "  File \"/home/runner/micromamba/envs/8186255/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 35, in _visit_source\n    raise FileNotFoundError(leaf)\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.9
    bioimageio_spec_version: 0.4.9
    error: null
    name: reproduce test outputs from test inputs (bioimageio.core 0.5.9)
    status: passed
    traceback: null
    warnings:
      non-validation-warnings: [Computed dataset percentiles naively by averaging
          percentiles of samples., 'Device management is not implemented for keras
          yet, cannot unload model']
  deepimagej:
  - {bioimageio_core_version: 0.5.9, bioimageio_spec_version: 0.4.9, error: Difference
      between CI and expected outputs is greater than threshold (CI produced an output
      image)., name: Reproduce test outputs with DeepImageJ headless., status: failed}
