bioimageio_core_version: 0.5.3.post2
bioimageio_spec_version: 0.4.5.post11
rdf_sha256: 220412a261d111ccefab18e8eaf4ca71b8785b28cd42ace8c987d5eb674c6972
status: passed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.5post11
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags for categories: [{''modality'': [''electron-microscopy'',
        ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'', ''transmission-light-microscopy'',
        ''super-resolution-microscopy'', ''x-ray-microscopy'', ''force-microscopy'',
        ''high-content-imaging'', ''whole-slide-imaging'', ''other'']}, {''dims'':
        [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''content'': [''cells'', ''nuclei'',
        ''extracellular-vesicles'', ''tissue'', ''plant'', ''mitochondria'', ''vasculature'',
        ''cell-membrane'', ''brain'', ''whole-organism'']}, {''framework'': [''tensorflow'',
        ''pytorch'', ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'',
        ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}, {''network'': [''unet'', ''densenet'',
        ''resnet'', ''inception'', ''shufflenet'']}, {''task'': [''semantic-segmentation'',
        ''instance-segmentation'', ''object-detection'', ''image-classification'',
        ''denoising'', ''image-restoration'', ''image-reconstruction'', ''in-silico-labeling'']}]'
      weights: {torchscript: missing 'pytorch_version'}
  - bioimageio_spec_version: 0.4.5post11
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags for categories: [{''modality'': [''electron-microscopy'',
        ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'', ''transmission-light-microscopy'',
        ''super-resolution-microscopy'', ''x-ray-microscopy'', ''force-microscopy'',
        ''high-content-imaging'', ''whole-slide-imaging'', ''other'']}, {''dims'':
        [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''content'': [''cells'', ''nuclei'',
        ''extracellular-vesicles'', ''tissue'', ''plant'', ''mitochondria'', ''vasculature'',
        ''cell-membrane'', ''brain'', ''whole-organism'']}, {''framework'': [''tensorflow'',
        ''pytorch'', ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'',
        ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}, {''network'': [''unet'', ''densenet'',
        ''resnet'', ''inception'', ''shufflenet'']}, {''task'': [''semantic-segmentation'',
        ''instance-segmentation'', ''object-detection'', ''image-classification'',
        ''denoising'', ''image-restoration'', ''image-reconstruction'', ''in-silico-labeling'']}]'
      weights: {torchscript: missing 'pytorch_version'}
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post11, error: null,
    name: reproduced test outputs from test inputs, status: passed, traceback: null}
  deepimagej:
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post7
    error: 'unsupported operand type(s) for +: ''PosixPath'' and ''str'''
    name: reproduce test outputs with deepimagej 2.1.13 using torchscript weights
    reason: error
    status: failed
    traceback: ["  File \"/home/runner/work/models/models/scripts/check_rdf_and_test_model.py\",
        line 122, in test_resource\n    error = (error or \"\") + download_deepimagej_model(fiji_path,
        rdf_path)\n", "  File \"/home/runner/work/models/models/scripts/utils.py\",
        line 27, in download_deepimagej_model\n    os.makedirs(fiji_dir + \"//models\")\n"]
  ilastik:
  - {bioimageio_core_version: 0.5.1, bioimageio_spec_version: 0.4.5post3, error: null,
    name: reproduce test outputs with ilastik 1.4.0b26 using torchscript weights,
    reason: null, status: passed, traceback: null}
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: 'Failed to download https://zenodo.org/api/files/9f580ca7-5f85-41ac-be2b-201172ed09b3/sample_output_0.tif
      (504 Server Error: Gateway Time-out for url: https://zenodo.org/api/files/9f580ca7-5f85-41ac-be2b-201172ed09b3/sample_output_0.tif)'
    name: reproduce test outputs with ilastik 1.4.0b27 using torchscript weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 39, in test_model\n    model_rdf, weights_priority_order=None if weight_format
        is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
        line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd,
        nodes_module=nodes)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 112, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path,
        uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)\n", "  File
        \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 60, in transform_list\n    return [self.transform(subnode, **kwargs)
        for subnode in node]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 60, in <listcomp>\n    return [self.transform(subnode, **kwargs) for
        subnode in node]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 206, in transform_URI\n    local_path = _resolve_source(node, root_path=self.root_path)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/functools.py\",
        line 840, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 212, in _resolve_source_uri_node\n    local_path = _download_url(path_or_remote_uri,
        output)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 396, in _download_url\n    raise RuntimeError(f\"Failed to download {uri}
        ({e})\")\n"]
  - {error: Missing/invalid weight formats for 10.5281/zenodo.6200999/6224243, name: reproduce
      test outputs with ilastik 1.4.0b26, reason: error, status: failed}
  - {error: Missing/invalid weight formats for 10.5281/zenodo.6200999/6224243, name: reproduce
      test outputs with ilastik 1.4.0b27, reason: error, status: failed}
